#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

cleanCase
rm -rf constant/polyMesh
rm -rf postProcessing
rm -rf log.*
rm -rf processor*
rm -rf *.foam
